// jobs.js
const jobs = [
  {
    id: "job1",
    title: "Harrisdale Installation",
    "House Type": "Single-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Concrete Tile",
    completionDate: "04-03-2025",
    difficulty: "Easy",
    timeToComplete: "(9:00am - 12:30pm)",
    suburb: "Harrisdale, WA, 6112",
    mainImage: "/images/Jobs/Job1/house.webp",
    additionalImages: [
      "/images/Jobs/Job1/panels1.webp",
      "/images/Jobs/Job1/panels2.webp",
      "/images/Jobs/Job1/inverter1.webp",
      "/images/Jobs/Job1/inverter2.webp",
    ]
  },
  {
    id: "job2",
    title: "Westminister Installation",
    "House Type": "Double-Storey",
    "Installation Type": "Battery + Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Metal Tin",
    completionDate: "05-03-2025",
    difficulty: "Easy",
    timeToComplete: "(7:00am - 11:34am)",
    suburb: "Westminister, WA, 6061",
    mainImage: "/images/Jobs/Job2/main.jpg",
    additionalImages: [
      "/images/Jobs/Job2/panels.jpg",
      "/images/Jobs/Job2/panels1.jpg",
      "/images/Jobs/Job2/panels1copy.jpg",
      "/images/Jobs/Job2/inverter:battery.jpg",
    ]
  },
  {
    id: "job3",
    title: "Mount Pleasant Installation",
    "House Type": "Double-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "13.2kW (30 panels)",
    roofType: "Clay Tile",
    completionDate: "06-03-2025",
    difficulty: "High",
    timeToComplete: "(7:30am-5:00pm)",
    suburb: "Mount Pleasant, WA, 6153",
    mainImage: "/images/Jobs/Job3/a6dd0bb1-aed1-411b-aeca-90c20a6df7f8.jpg",
    additionalImages: [
      "/images/Jobs/Job3/48771b1d-ce9c-4f01-a632-e3141255724e.jpg",
      "/images/Jobs/Job3/a71afa1a-b842-427c-abc2-eed41bc355b9.jpg",
      "/images/Jobs/Job3/a71afa1a-b842-427c-abc2-eed41bc355b9copy.jpg",
      "/images/Jobs/Job3/ed3d4d52-21e3-4755-9fe3-e1c8c2b8de40.jpg",
    ]
  },
  {
    id: "job4",
    title: "Alexander Heights Installation",
    "House Type": "Single-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Concrete Tile",
    completionDate: "07-03-2025",
    difficulty: "Easy",
    timeToComplete: "(7:00am-11:20am)",
    suburb: "Alexander Heights, 6064",
    mainImage: "/images/Jobs/Job4/df5cb2b5-c55b-477f-a8a5-31e5eeb53ab4.jpg",
    additionalImages: [
      "/images/Jobs/Job4/e2fded1a-6a90-446e-b64f-52567e2c61b8.jpg",
      "/images/Jobs/Job4/ba923769-b190-4e74-b7d5-c5ee831ec7fb.jpg",
      "/images/Jobs/Job4/296592db-fcc6-4bcb-85ee-710e841bf76c.jpg",
      "/images/Jobs/Job4/5207bfe2-040f-45d2-98ef-f6bd97426d45.jpg",
    ]
  },
  {
    id: "job5",
    title: "Two Rocks Installation",
    "House Type": "Single-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Metal Tin",
    completionDate: "07-03-2025",
    difficulty: "Easy",
    timeToComplete: "(12:30pm-4:00pm)",
    suburb: "Two Rocks, WA, 6037",
    mainImage: "/images/Jobs/Job5/24841301-396b-41c8-a7af-6e6f505f29f8.jpg",
    additionalImages: [
      "/images/Jobs/Job5/da54523a-2d7d-4253-abfc-33ca0cb63f62.jpg",
      "/images/Jobs/Job5/4f0bd18a-c425-43fc-af48-0ee40c2d460a.jpg",
      "/images/Jobs/Job5/ee8b5e94-f9fd-4eeb-8339-2bf6eaadbcb2.jpg",
      "/images/Jobs/Job5/91170244-36a7-417b-97bf-90eb6da330c8.jpg",
    ]
  },
  {
    id: "job6",
    title: "Kardinya Installation",
    "House Type": "Single-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Clay Tile",
    completionDate: "10-03-2025",
    difficulty: "Easy",
    timeToComplete: "(8:45am-12:00pm)",
    suburb: "Kardinya, WA, 6163",
    mainImage: "/images/Jobs/Job6/Screenshot 2025-03-11 at 2.29.26 pm.png",
    additionalImages: [
      "/images/Jobs/Job6/dj6x8tprrc3aqt1lwslw.webp",
      "/images/Jobs/Job6/ikks9mlyrfz1cjwuga0b.webp",
      "/images/Jobs/Job6/ccjarhy6fomzku85sw9s.webp",
      "/images/Jobs/Job6/vqc2wtzi3obwz2pdgg3r.webp",
    ]
  },
  {
    id: "job7",
    title: "St James Installation",
    "House Type": "Double-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Metal Tin",
    completionDate: "10-03-2025",
    difficulty: "Easy",
    timeToComplete: "(1:30pm-4:00pm)",
    suburb: "St James, WA, 6102",
    mainImage: "/images/Jobs/Job7/c4cba490-642e-409d-8e82-a5400385acbc.webp",
    additionalImages: [
      "/images/Jobs/Job7/75a6cbd6-cc41-4001-ac75-5b10a8f34d28.webp",
      "/images/Jobs/Job7/83b35a29-2075-484f-b651-3ca17a7a716c.webp",
      "/images/Jobs/Job7/27fc3f48-fc6e-4912-b14b-6f44b17583f8.webp",
      "/images/Jobs/Job7/d8da588a-26b0-4a0f-a156-d4ff90fa593e.webp",
    ]
  },
  {
    id: "job8",
    title: "Victoria Park Installation",
    "House Type": "Double-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Metal Tin",
    completionDate: "12-03-2025",
    difficulty: "Moderate",
    timeToComplete: "(8:45am-1:15pm)",
    suburb: "Victoria Park, WA, 6100",
    mainImage: "/images/Jobs/Job8/m.jpg",
    additionalImages: [
      "/images/Jobs/Job8/p1.jpg",
      "/images/Jobs/Job8/p2.jpg",
      "/images/Jobs/Job8/i1.jpg",
      "/images/Jobs/Job8/i2.jpg",
    ]
  },
  {
    id: "job9",
    title: "Applecross Installation",
    "House Type": "Double-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Metal Tin",
    completionDate: "13-03-2025",
    difficulty: "Moderate",
    timeToComplete: "(7:45am-10:35am)",
    suburb: "Applecross, WA, 6153",
    mainImage: "/images/Jobs/Job9/m.webp",
    additionalImages: [
      "/images/Jobs/Job9/p1.webp",
      "/images/Jobs/Job9/p2.webp",
      "/images/Jobs/Job9/i1.webp",
      "/images/Jobs/Job9/i2.webp",
    ]
  },
  {
    id: "job10",
    title: "Bayswater Installation",
    "House Type": "Double-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Clay Tile",
    completionDate: "14-03-2025",
    difficulty: "Moderate",
    timeToComplete: "(8:30am-12:15pm)",
    suburb: "Bayswater, WA, 6053",
    mainImage: "/images/Jobs/Job10/m.webp",
    additionalImages: [
      "/images/Jobs/Job10/p1.webp",
      "/images/Jobs/Job10/p2.webp",
      "/images/Jobs/Job10/i1.webp",
      "/images/Jobs/Job10/i2.webp",
    ]
  },
  {
    id: "job11",
    title: "Victoria Park Installation",
    "House Type": "Single-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Clay Tile",
    completionDate: "14-03-2025",
    difficulty: "Moderate",
    timeToComplete: "(1:20pm-4:33pm)",
    suburb: "Victoria Park, WA, 6100",
    mainImage: "/images/Jobs/Job11/m.webp",
    additionalImages: [
      "/images/Jobs/Job11/p1.webp",
      "/images/Jobs/Job11/p2.webp",
      "/images/Jobs/Job11/i1.webp",
      "/images/Jobs/Job11/i2.webp",
    ]
  },
  {
    id: "job12",
    title: "Wilson Installation",
    "House Type": "Single-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "9.96kW (21 Panels)",
    roofType: "Metal Tin",
    completionDate: "17-03-2025",
    difficulty: "Moderate",
    timeToComplete: "(7:20am-12:00pm)",
    suburb: "Wilson, WA, 6107",
    mainImage: "/images/Jobs/Job12/m.webp",
    additionalImages: [
      "/images/Jobs/Job12/p1.webp",
      "/images/Jobs/Job12/p2.webp",
      "/images/Jobs/Job12/i1.webp",
      "/images/Jobs/Job12/i2.webp",
    ]
  },
  {
    id: "job13",
    title: "Pearsall Installation",
    "House Type": "Single-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Metal Tin",
    completionDate: "17-03-2025",
    difficulty: "Easy",
    timeToComplete: "(2:00pm-4:30pm)",
    suburb: "Pearsall, WA, 6065",
    mainImage: "/images/Jobs/Job13/m.webp",
    additionalImages: [
      "/images/Jobs/Job13/p1.webp",
      "/images/Jobs/Job13/p2.webp",
      "/images/Jobs/Job13/i1.webp",
      "/images/Jobs/Job13/i2.webp",
    ]
  },
  {
    id: "job14",
    title: "Brabham Installation",
    "House Type": "Single-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Metal Tin",
    completionDate: "18-03-2025",
    difficulty: "Easy",
    timeToComplete: "(7:15am-10:00am)",
    suburb: "Brabham, WA, 6055",
    mainImage: "/images/Jobs/Job14/m.webp",
    additionalImages: [
      "/images/Jobs/Job14/p1.webp",
      "/images/Jobs/Job14/p2.webp",
      "/images/Jobs/Job14/i1.webp",
      "/images/Jobs/Job14/i2.webp",
    ]
  },
  {
    id: "job15",
    title: "Hammilton Hill Installation",
    "House Type": "Single-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.65kW (14 Panels)",
    roofType: "Concrete Tile",
    completionDate: "19-03-2025",
    difficulty: "Easy",
    timeToComplete: "(7:00am-11:40am)",
    suburb: "Hammilton Hill, WA, 6163",
    mainImage: "/images/Jobs/Job15/m.webp",
    additionalImages: [
      "/images/Jobs/Job15/p1.webp",
      "/images/Jobs/Job15/p2.webp",
      "/images/Jobs/Job15/i1.webp",
      "/images/Jobs/Job15/i2.webp",
    ]
  },
  {
    id: "job16",
    title: "Landsdale Installation",
    "House Type": "Single-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.44kW (14 Panels)",
    roofType: "Metal Tin",
    completionDate: "24-03-2025",
    difficulty: "Easy",
    timeToComplete: "(8:30am-12:15pm)",
    suburb: "Landsdale, WA, 6065",
    mainImage: "/images/Jobs/Job16/m.webp",
    additionalImages: [
      "/images/Jobs/Job16/p1.webp",
      "/images/Jobs/Job16/p2.webp",
      "/images/Jobs/Job16/i1.webp",
      "/images/Jobs/Job16/i2.webp",
    ]
  },
  {
    id: "job17",
    title: "Sinagra Installation",
    "House Type": "Single-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Clay Tile",
    completionDate: "25-03-2025",
    difficulty: "Easy",
    timeToComplete: "(8:45am-2:15pm)",
    suburb: "Sinagra, WA, 6065",
    mainImage: "/images/Jobs/Job17/m.webp",
    additionalImages: [
      "/images/Jobs/Job17/p1.webp",
      "/images/Jobs/Job17/p2.webp",
      "/images/Jobs/Job17/i1.webp",
      "/images/Jobs/Job17/i2.webp",
    ]
  },
  {
    id: "job18",
    title: "Banksia Grove Install",
    "House Type": "Single-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Metal Tin",
    completionDate: "26-03-2025",
    difficulty: "Easy",
    timeToComplete: "(9am-11am)",
    suburb: "Banksia Grove, WA, 6031",
    mainImage: "/images/Jobs/Job18/m.webp",
    additionalImages: [
      "/images/Jobs/Job18/p1.webp",
      "/images/Jobs/Job18/p2.webp",
      "/images/Jobs/Job18/i1.webp",
      "/images/Jobs/Job18/i2.webp",
    ]
  },
  {
    id: "job19",
    title: "Wilson Installation",
    "House Type": "Single-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Clay Tile",
    completionDate: "27-03-2025",
    difficulty: "Easy",
    timeToComplete: "(7:00am-11:15am)",
    suburb: "Wilson, WA, 6107",
    mainImage: "/images/Jobs/Job19/m.webp",
    additionalImages: [
      "/images/Jobs/Job19/p1.webp",
      "/images/Jobs/Job19/p2.webp",
      "/images/Jobs/Job19/i1.webp",
      "/images/Jobs/Job19/i2.webp",
    ]
  },
  {
    id: "job20",
    title: "Parkerville Installation",
    "House Type": "Single-Storey",
    "Installation Type": "Solar + Battery",
    "System Size": "8.36kW (19 Panels)",
    roofType: "Metal Tin",
    completionDate: "28-03-2025",
    difficulty: "Easy",
    timeToComplete: "(7:10am-11:30am)",
    suburb: "Parkerville, WA, 6081",
    mainImage: "/images/Jobs/Job20/m.webp",
    additionalImages: [
      "/images/Jobs/Job20/p1.webp",
      "/images/Jobs/Job20/p2.webp",
      "/images/Jobs/Job20/i1.webp",
      "/images/Jobs/Job20/i2.webp",
    ]
  },
  {
    id: "job21",
    title: "Aubin Grove Install",
    "House Type": "Single-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Concrete Tile",
    completionDate: "31-03-2025",
    difficulty: "Easy",
    timeToComplete: "(7:00am-10:30am)",
    suburb: "Aubin Grove, WA, 6164",
    mainImage: "/images/Jobs/Job21/m.webp",
    additionalImages: [
      "/images/Jobs/Job21/p1.webp",
      "/images/Jobs/Job21/p2.webp",
      "/images/Jobs/Job21/i1.webp",
      "/images/Jobs/Job21/i2.webp",
    ]
  },
  {
    id: "job22",
    title: "Riverton Installation",
    "House Type": "Single-Storey",
    "Installation Type": "Normal Solar",
    "System Size": "6.6kW (15 Panels)",
    roofType: "Concrete Tile",
    completionDate: "01-04-2025",
    difficulty: "Easy",
    timeToComplete: "(7:00am-10:30am)",
    suburb: "Riverton, WA, 6148",
    mainImage: "/images/Jobs/Job22/m.webp",
    additionalImages: [
      "/images/Jobs/Job22/p1.webp",
      "/images/Jobs/Job22/p2.webp",
      "/images/Jobs/Job22/i1.webp",
      "/images/Jobs/Job22/i2.webp",
    ]
  }
];

// Make jobs globally available
window.jobs = jobs;